### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kennyparsons** [Receipt-Wrangler/receipt-wrangler-api#198] opened 2024-03-17 03:21 UTC
Hello, this is similar to a previous issue that has not been resolved. 

1. The compose file:
```yaml
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wrangler
      PGUSER: wrangler
      POSTGRES_PASSWORD: redacted
      POSTGRES_DB: wrangler
    volumes:
      - /var/lib/docker/wrangler/pgsql:/var/lib/pgsql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    image: noah231515/receipt-wrangler-desktop:latest
    restart: always
    ports:
      - 9081:80
  api:
    image: noah231515/receipt-wrangler-api:latest
    restart: always
    working_dir: /go/api
    command: ./api --env prod
    ports:
      - 9080:8081
    volumes:
      - /var/lib/docker/wrangler/config:/go/api/config
      - /var/lib/docker/wrangler/data:/go/api/data
      - /var/lib/docker/wrangler/logs:/go/api/logs
    depends_on:
      db:
        condition: service_healthy
```
2. The issue: api container exits immediately with a panic:
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7fcdf2]
api-1       |
goroutine 1 [running]:
gorm.io/gorm.(*DB).getInstance(0x8?)
	/go/pkg/mod/gorm.io/gorm@v1.25.7/gorm.go:399 +0x12
gorm.io/gorm.(*DB).Migrator(0x421e25?)
	/go/pkg/mod/gorm.io/gorm@v1.25.7/migrator.go:12 +0x13
gorm.io/gorm.(*DB).AutoMigrate(0x0?, {0xc0003d6d80, 0x11, 0x11})
	/go/pkg/mod/gorm.io/gorm@v1.25.7/migrator.go:24 +0x25
receipt-wrangler/api/internal/repositories.MakeMigrations()
	/go/api/internal/repositories/db.go:81 +0x3e5
main.main()
	/go/api/main.go:47 +0x2d1
```
3. The full compose up log:
```
root@receipt-wrangler:~/wrangler# docker compose up
[+] Running 4/4
 ✔ Network wrangler_default       Created                                                                                                                                                                                                0.4s
 ✔ Container wrangler-frontend-1  Created                                                                                                                                                                                                2.8s
 ✔ Container wrangler-db-1        Created                                                                                                                                                                                                2.9s
 ✔ Container wrangler-api-1       Created                                                                                                                                                                                                1.8s
Attaching to api-1, db-1, frontend-1
frontend-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
frontend-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
frontend-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
frontend-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
frontend-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
frontend-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
frontend-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: using the "epoll" event method
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: nginx/1.25.4
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10)
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: OS: Linux 5.15.102-1-pve
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 524288:524288
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: start worker processes
frontend-1  | 2024/03/17 03:07:20 [notice] 1#1: start worker process 28
db-1        | The files belonging to this database system will be owned by user "postgres".
db-1        | This user must also own the server process.
db-1        |
db-1        | The database cluster will be initialized with locale "en_US.utf8".
db-1        | The default database encoding has accordingly been set to "UTF8".
db-1        | The default text search configuration will be set to "english".
db-1        |
db-1        | Data page checksums are disabled.
db-1        |
db-1        | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1        | creating subdirectories ... ok
db-1        | selecting dynamic shared memory implementation ... posix
db-1        | selecting default max_connections ... 100
db-1        | selecting default shared_buffers ... 128MB
db-1        | selecting default time zone ... Etc/UTC
db-1        | creating configuration files ... ok
db-1        | running bootstrap script ... ok
db-1        | performing post-bootstrap initialization ... ok
db-1        | syncing data to disk ... ok
db-1        |
db-1        | initdb: warning: enabling "trust" authentication for local connections
db-1        | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1        |
db-1        | Success. You can now start the database server using:
db-1        |
db-1        |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1        |
db-1        | waiting for server to start....2024-03-17 03:07:24.529 UTC [46] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1        | 2024-03-17 03:07:24.775 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1        | 2024-03-17 03:07:25.146 UTC [49] LOG:  database system was shut down at 2024-03-17 03:07:22 UTC
db-1        | .2024-03-17 03:07:25.281 UTC [46] LOG:  database system is ready to accept connections
db-1        |  done
db-1        | server started
db-1        | CREATE DATABASE
db-1        |
db-1        |
db-1        | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1        |
db-1        | 2024-03-17 03:07:26.331 UTC [46] LOG:  received fast shutdown request
db-1        | waiting for server to shut down....2024-03-17 03:07:26.478 UTC [46] LOG:  aborting any active transactions
db-1        | 2024-03-17 03:07:26.483 UTC [46] LOG:  background worker "logical replication launcher" (PID 52) exited with exit code 1
db-1        | 2024-03-17 03:07:26.483 UTC [47] LOG:  shutting down
db-1        | 2024-03-17 03:07:26.619 UTC [47] LOG:  checkpoint starting: shutdown immediate
db-1        | ..2024-03-17 03:07:28.827 UTC [65] FATAL:  the database system is shutting down
db-1        | 2024-03-17 03:07:29.224 UTC [47] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.294 s, sync=1.715 s, total=2.742 s; sync files=301, longest=0.517 s, average=0.006 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913078, redo lsn=0/1913078
db-1        | 2024-03-17 03:07:29.229 UTC [46] LOG:  database system is shut down
db-1        |  done
db-1        | server stopped
db-1        |
db-1        | PostgreSQL init process complete; ready for start up.
db-1        |
db-1        | 2024-03-17 03:07:29.754 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1        | 2024-03-17 03:07:29.755 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1        | 2024-03-17 03:07:29.755 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1        | 2024-03-17 03:07:30.031 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1        | 2024-03-17 03:07:30.325 UTC [69] LOG:  database system was shut down at 2024-03-17 03:07:29 UTC
db-1        | 2024-03-17 03:07:30.468 UTC [1] LOG:  database system is ready to accept connections
api-1       | panic: runtime error: invalid memory address or nil pointer dereference
api-1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7fcdf2]
api-1       |
api-1       | goroutine 1 [running]:
api-1       | gorm.io/gorm.(*DB).getInstance(0x8?)
api-1       | 	/go/pkg/mod/gorm.io/gorm@v1.25.7/gorm.go:399 +0x12
api-1       | gorm.io/gorm.(*DB).Migrator(0x421e25?)
api-1       | 	/go/pkg/mod/gorm.io/gorm@v1.25.7/migrator.go:12 +0x13
api-1       | gorm.io/gorm.(*DB).AutoMigrate(0x0?, {0xc0003d6d80, 0x11, 0x11})
api-1       | 	/go/pkg/mod/gorm.io/gorm@v1.25.7/migrator.go:24 +0x25
api-1       | receipt-wrangler/api/internal/repositories.MakeMigrations()
api-1       | 	/go/api/internal/repositories/db.go:81 +0x3e5
api-1       | main.main()
api-1       | 	/go/api/main.go:47 +0x2d1
api-1 exited with code 0
```
4. my config.prod.json
```json
{
  "secretKey": "redacted",
  "features": {
    "enableLocalSignUp": false,
    "aiPoweredReceipts": false
  },
  "database": {
    "user": "wrangler",
    "password": "redacted",
    "name": "wrangler",
    "host": "db",
    "port": "5432",
    "engine": "postgresql"
  }
}
```

**Comment by Noah231515** [comment] 2024-03-17 06:14
Hey Kenny,
Thanks for all of this detail. Just wanted to confirm that I can reproduce this issue on my side.
I'll take a closer look at this in the morning and see what's going on.

**Comment by Noah231515** [comment] 2024-03-17 16:33
@kennyparsons 
Hey Kenny,
This has been fixed by #199. (Race condition with reading the config file)
Try taking down the compose stack, pulling the latest images in the stack and restarting the stack.

Let me know if the issue has been resolved.

**Comment by kennyparsons** [comment] 2024-03-17 20:08
new issue:
```
api-1       |
api-1       | 2024/03/17 20:05:44 /go/api/internal/repositories/db.go:54
api-1       | [error] failed to initialize database, got error cannot parse `host=db user=wrangler password=xxxxx dbname=wrangler port=0 sslmode=disable`: invalid port (outside range)
api-1 exited with code 0
```
Did the config look right? some versions have host var with host:port. Some are split into host and port vars.

**Comment by Noah231515** [comment] 2024-03-17 20:17
@kennyparsons  Looks like the port should be a number instead of a string. Remove the double quotes around "5432" and you should be good to go.

**Comment by kennyparsons** [comment] 2024-03-17 21:25
Ah. I always forget that. Thanks! Issue closed.

**Closed** 2024-03-17 21:25 UTC
